import os

filepath = r"c:\APP\GestorPrefeitura\src\nfse_bot.py"
with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# In the current file, line 337 to 516 corresponds to 
# data_raw = competencia_mes_ano.replace...
# until log_exec("SUCESSO", "Arquivo consolidado...")

# Since we want to replace from line 337 to 516, we know:
start_idx = 336 # 0-indexed for line 337
end_idx = 516   # 0-indexed for line 517 (exclusive)

new_block = [
"""                # NOVO LOOP DE MÚLTIPLOS AGRUPAMENTOS: Prestados e Tomados\n""",
"""                for tipo_agrupamento, tipo_sigla in [('Serviços Prestados', 'ptd'), ('Serviços Tomados', 'tmd')]:\n""",
"""                    if log_callback: log_callback(f"Extraindo {tipo_agrupamento}...")\n""",
"""                    try:\n""",
"""                        # 3. Informar o Agrupamento no form do Primefaces\n""",
"""                        try:\n""",
"""                            lbl_agrup = page.locator('label', has_text='Agrupamento').first\n""",
"""                            if lbl_agrup.is_visible():\n""",
"""                                lbl_agrup.locator('xpath=..').locator('.ui-selectonemenu-trigger').click(force=True)\n""",
"""                                time.sleep(1)\n""",
"""                                item_tipo = page.locator(f'li.ui-selectonemenu-item:has-text("{tipo_agrupamento}")').first\n""",
"""                                if item_tipo.is_visible():\n""",
"""                                    item_tipo.click(force=True)\n""",
"""                                else:\n""",
"""                                    js_click_text('li.ui-selectonemenu-item', tipo_agrupamento)\n""",
"""                                time.sleep(1)\n""",
"""                        except Exception as e:\n""",
"""                            print(f"Nota: não foi possível mudar 'Agrupamento' para {tipo_agrupamento}. Erro: {e}")\n""",
"""\n""",
"""                        # 4. Informar Datas e Filtros no form\n""",
"""                        data_raw = competencia_mes_ano.replace("/", "")\n""",
"""                        \n""",
"""                        inp_ini = page.locator('input[id$="idStart_input"]').first\n""",
"""                        inp_ini.clear()\n""",
"""                        inp_ini.type(data_raw, delay=50)\n""",
"""                        \n""",
"""                        inp_end = page.locator('input[id$="idEnd_input"]').first\n""",
"""                        inp_end.clear()\n""",
"""                        inp_end.type(data_raw, delay=50)\n""",
"""                        \n""",
"""                        # Marcar Todos situacao e Exigibilidade (Super Primefaces Checkbox Hack)\n""",
"""                        page.evaluate('''() => {\n""",
"""                            // Clica na caixa estilizada visual do Primefaces caso não esteja checada\n""",
"""                            document.querySelectorAll('.ui-chkbox-box:not(.ui-state-active)').forEach(el => el.click());\n""",
"""                            \n""",
"""                            // Força o checkbox escondido internamente para 'true' por segurança\n""",
"""                            document.querySelectorAll('input[type="checkbox"]').forEach(el => {\n""",
"""                                if (!el.checked) {\n""",
"""                                    el.checked = true;\n""",
"""                                    el.dispatchEvent(new Event('change', { bubbles: true }));\n""",
"""                                }\n""",
"""                            });\n""",
"""                        }''')\n""",
"""                                \n""",
"""                        # Clica Pesquisar para carregar a tabela!\n""",
"""                        js_click_text('a', 'Pesquisar')\n""",
"""                        time.sleep(4)\n""",
"""                                \n""",
"""                        # 5. Tentar encontrar a Saída "Excel" antes de clicar no export / gerar\n""",
"""                        try:\n""",
"""                            # 1. Clicar na caixa de dropdown Saída via Playwright para garantir que o evento Focus/Click ocorra no DOM real\n""",
"""                            lbl_saida = page.locator('label', has_text='Saída').first\n""",
"""                            if lbl_saida.is_visible():\n""",
"""                                # Clica na seta apontadora (trigger) do select correspondente\n""",
"""                                lbl_saida.locator('xpath=..').locator('.ui-selectonemenu-trigger').click(force=True)\n""",
"""                                time.sleep(1)\n""",
"""                                \n""",
"""                                # 2. Clicar na opção Excel na lista renderizada no fim do HTML\n""",
"""                                item_excel = page.locator('li.ui-selectonemenu-item:has-text("Excel"), li.ui-selectonemenu-item:has-text("XLS")').first\n""",
"""                                if item_excel.is_visible():\n""",
"""                                    item_excel.click(force=True)\n""",
"""                                else:\n""",
"""                                    js_click_text('li.ui-selectonemenu-item', 'Excel')\n""",
"""                                time.sleep(1)\n""",
"""                        except Exception as e:\n""",
"""                            print(f"Nota: não foi possível mudar a 'Saída' para Excel pelo dropdown. Continuando... Erro: {e}")\n""",
"""\n""",
"""                        # 6. Baixar Excel\n""",
"""                        print(f"Aguardando geracao do excel ou mensagem de erro (vazio) para {tipo_sigla}...")\n""",
"""                        \n""",
"""                        btn_excel = None\n""",
"""                        for selector in [\n""",
"""                            'a:has-text("Download")', \n""",
"""                            'button:has-text("Download")', \n""",
"""                            'button:has-text("Excel")', \n""",
"""                            'a:has-text("XLS")', \n""",
"""                            'button:has-text("Gerar")', \n""",
"""                            'button:has-text("Imprimir")', \n""",
"""                            'a.ui-commandlink:has(i.pi-file-excel)'\n""",
"""                        ]:\n""",
"""                            element = page.locator(selector).first\n""",
"""                            if element.is_visible():\n""",
"""                                btn_excel = element\n""",
"""                                break\n""",
"""                                \n""",
"""                        if not btn_excel:\n""",
"""                            print(f"Botão de Excel não localizado para {tipo_sigla}. Capturando tela.")\n""",
"""                            page.screenshot(path=os.path.join(errors_dir, f"erro_btn_excel_{cnpj}_{tipo_sigla}_{timestamp_log}.png"))\n""",
"""                            btn_excel = page.locator('button[type="submit"]').first\n""",
"""                            \n""",
"""                        # Configura a captura do download em background\n""",
"""                        download_obj = [None]\n""",
"""                        def handle_download(d):\n""",
"""                            download_obj[0] = d\n""",
"""                            \n""",
"""                        page.on("download", handle_download)\n""",
"""                        btn_excel.click()\n""",
"""                        \n""",
"""                        # Loop de espera (Polling) para verificar se o download iniciou OU se deu erro de "Nenhum registro"\n""",
"""                        has_error = False\n""",
"""                        timeout_count = 0\n""",
"""                        while timeout_count < 120:\n""",
"""                            if download_obj[0]:\n""",
"""                                break\n""",
"""                                \n""",
"""                            # Verifica a mensagem de erro vermelha no painel informando que nao tem notas\n""",
"""                            if page.get_by_text("Nenhum registro", exact=False).first.is_visible():\n""",
"""                                has_error = True\n""",
"""                                break\n""",
"""                                    \n""",
"""                            page.wait_for_timeout(1000)\n""",
"""                            timeout_count += 1\n""",
"""                            \n""",
"""                        # Limpa o listener\n""",
"""                        page.remove_listener("download", handle_download)\n""",
"""                        \n""",
"""                        if has_error:\n""",
"""                            print(f"Empresa {cnpj} não possui notas {tipo_agrupamento} na competência {competencia_mes_ano}.")\n""",
"""                            if log_callback: log_callback(f"📂 {cnpj} não possui notas {tipo_sigla} no período (Zerado).")\n""",
"""                            log_exec(cnpj, nome_empresa, competencia_mes_ano, "VAZIO", f"Sem notas de {tipo_agrupamento}.", index=idx, total=total_targets, csv_path=csv_log_path)\n""",
"""                            continue \n""",
"""                            \n""",
"""                        if not download_obj[0]:\n""",
"""                            log_exec(cnpj, nome_empresa, competencia_mes_ano, "ERRO_TIMEOUT", f"Timeout aguardando download {tipo_sigla}", index=idx, total=total_targets, csv_path=csv_log_path)\n""",
"""                            print(f"Timeout no {tipo_sigla} da empresa {cnpj}")\n""",
"""                            continue\n""",
"""                            \n""",
"""                        download = download_obj[0]\n""",
"""                        sugg_ext = download.suggested_filename.split('.')[-1]\n""",
"""                        if not sugg_ext: sugg_ext = 'xlsx'\n""",
"""                        \n""",
"""                        nome_seguro = nome_empresa.replace('/', '-').replace('\\\\', '-').strip()\n""",
"""                        if not nome_seguro:\n""",
"""                            nome_seguro = 'empresa'\n""",
"""                            \n""",
"""                        out_dir = output_dir if output_dir else LIVROS_DIR\n""",
"""                        \n""",
"""                        # NOVO PADRÃO DE NOME + RESILIENCIA COM (1), (2), etc\n""",
"""                        base_filename = f"{competencia_mes_ano.replace('/','')}-{tipo_sigla}-{nome_seguro}"\n""",
"""                        filepath = os.path.join(out_dir, f"{base_filename}.{sugg_ext}")\n""",
"""                        \n""",
"""                        counter = 1\n""",
"""                        while os.path.exists(filepath):\n""",
"""                            filepath = os.path.join(out_dir, f"{base_filename}({counter}).{sugg_ext}")\n""",
"""                            counter += 1\n""",
"""                            \n""",
"""                        download.save_as(filepath)\n""",
"""                        print(f"Download salvo em: {filepath}")\n""",
"""                        if log_callback: log_callback(f"💾 Arquivo {tipo_sigla} salvo: {os.path.basename(filepath)}")\n""",
"""                        \n""",
"""                        # 7. Processamento e Totais Ocultos\n""",
"""                        sucesso_totais = process_livro_fiscal(filepath, target, competencia_mes_ano)\n""",
"""                        if sucesso_totais:\n""",
"""                            log_exec(cnpj, nome_empresa, competencia_mes_ano, "SUCESSO", f"Arquivo {tipo_sigla.upper()} salvo com Totais", index=idx, total=total_targets, csv_path=csv_log_path)\n""",
"""                        else:\n""",
"""                            log_exec(cnpj, nome_empresa, competencia_mes_ano, "SUCESSO_PARCIAL", f"Arquivo {tipo_sigla.upper()} salvo, mas falha ao injetar Totais Localmente", index=idx, total=total_targets, csv_path=csv_log_path)\n""",
"""                            \n""",
"""                    except Exception as loop_e:\n""",
"""                        print(f"Erro processando {tipo_sigla} de {cnpj}: {loop_e}")\n""",
"""                        log_exec(cnpj, nome_empresa, competencia_mes_ano, "ERRO_TIPO", f"Falha no tipo {tipo_sigla}: {loop_e}", index=idx, total=total_targets, csv_path=csv_log_path)\n"""
]

# We join unmodified + new_block + unmodified
final_lines = lines[:start_idx] + new_block + lines[end_idx:]

with open(filepath, 'w', encoding='utf-8') as f:
    f.writelines(final_lines)

print("Substituição concluída com sucesso.")
